export const GET_ITEM = "ITEM_GETITEM"
export const GET_WEATHER = "WEATHER_GETWEATHER"
export const GET_CHARTS = "CHARTS_GETDATA"
export const GET_USER = "USER_GETUSER"
export const USER_ADD = "USER_ADD"
export const GET_LOGIN = "LOGIN_STATUS"
